export * as Blockly from "blockly"
export * as Init from "./categories/initialization"

import "./blocks/variables"
import "./blocks/functions"
import "./blocks/datatypes"
import "./blocks/monads"
import "./blocks/tuples"
import "./blocks/lists"
import "./blocks/logic"
import "./blocks/text"
import "./blocks/io"
